sudo: false

# language: python
language: c

python:
    - "2.7"

# Environment variable for documentation deployment
# Change author email when website author changes
env:
  global:
  - ENCRYPTION_LABEL: "1909213e8aea"
  - COMMIT_AUTHOR_EMAIL: "pandolfovince@gmail.com"

matrix:
  include:
    - os: linux
      env: DEVITO_ARCH=gcc DEVITO_OPENMP=0
    - os: linux
      env: DEVITO_ARCH=gcc DEVITO_OPENMP=1 OMP_NUM_THREADS=2
  allow_failures:
    - os: osx
      env: DEVITO_ARCH=clang DEVITO_OPENMP=0

addons:
  apt:
    packages:
        - python-dev
        - python-pip

install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; brew install python; brew link --overwrite python ; fi
  - pip install --user -U pip
  - pip install --user -r requirements.txt
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PATH=$PATH:$HOME/Library/Python/2.7/bin; fi

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - export PYTHONPATH=$PYTHONPATH:$PWD
  - flake8 --builtins=ArgumentError .
  - isort --check-only **/*.py
  - py.test -vs tests/
  - python examples/benchmark.py test -P tti -a -d 20 20 20 -n 5
  - python examples/benchmark.py test -P acoustic -a
  - py.test -vs examples/diffusion/example_diffusion.py
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ./docs/deploy.sh; fi
