name: devito
channels:
  - defaults
  - conda-forge
  - omnia  # pytest-ipynb
dependencies:
  - numpy >=1.11
  - sympy ==1.0
  - matplotlib
  - pytest
  - pytest-ipynb
  - flake8>=2.1.0
  - cached-property
  - py-cpuinfo
  - psutil>=5.1.0
  - pip:
    - "git+git://github.com/inducer/cgen"
    - "git+git://github.com/inducer/codepy"
